name: test-notebooks
on:
  [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: install requirements
        run: |
          pip install -r ./requirements.txt && pip install pytest nbmake
      - name: Run test suite
        run: |
          pytest --nbmake notebooks/*ipynb